[server]
Port = 8080
ReadHeaderTimeout = "15s"
ReadTimeout = "30s"
WriteTimeout = "30s"
IdleTimeout = "60s"


[database]
dsn = "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
enabled = false
enableMigration = false

[cache]
enabled=false